#main docker-compose for dev env
version: '3.9'

services:
  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: webshop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    healthcheck:
      test: "exit 0"
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server --console-address ":9090" /data

  backend:
    build:
      context: ./webshop-be
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: local
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin
      MONITORING_USERNAME: monitoring
      MONITORING_PASSWORD: monitoring
      API_USERNAME: swagger
      API_PASSWORD: swagger
      CLIENT_ORIGIN: http://localhost:3000 #fe container
      SMTP_HOST: maildev
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      JWT_ACCESS_SECRET: generate
      JWT_REFRESH_SECRET: generate
      DEMO_MODE: true
      ENDPOINT_SECRET: MUST_BE_SPECIFIED
      STRIPE_PRIVATE_KEY: MUST_BE_SPECIFIED
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    depends_on:
      - postgres
      - maildev
      - minio
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./webshop-fe
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL=http://localhost:8080
    ports:
      - "5173:80"


volumes:
  postgres-db:
    driver: local
  minio-data:
    driver: local