services:
  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: webshop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    healthcheck:
      test: "exit 0"
    ports:
      - "5432:5432"
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000" # API
      - "9090:9090" # Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server --console-address ":9090" /data

volumes:
  postgres-db:
    driver: local
  minio-data:
    driver: local