spring:
  mail:
    host: ${SMTP_PORT:smtp.gmail.com}
    port: ${SMTP_HOST:587}
    username: ${SMTP_USERNAME:gmail_placeholder}
    password: ${SMTP_PASSWORD:gmail_password_placeholder}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: ${KEYSTORE_PASSWORD:pass123}
    key-store-type: PKCS12
    key-alias: webshop
    enabled: true

application:
  email:
    new-password: http://localhost:4200/home?forgotPassword=true&id={id} # todo domain
    verify: http://localhost:4200/home?emailVerification=true&id={id} # todo domain
    more-info: http://localhost:4200/order?id={id} # todo from frontend
    from: noreply@${WEBSHOP_NAME:webshop}.hu
