spring:
  mail:
    host: ${SMTP_PORT:smtp.gmail.com}
    port: ${SMTP_HOST:587}
    username: ${SMTP_USERNAME:gmail_placeholder}
    password: ${SMTP_PASSWORD:gmail_password_placeholder}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: ${KEYSTORE_PASSWORD:pass123}
    key-store-type: PKCS12
    key-alias: webshop
    enabled: true

application:
  email:
    new-password: http://localhost:3000/new-password?id={id} # todo extract path, use prod domain
    verify: http://localhost:3000/verify-email/confirm?id={id}
    more-info: http://localhost:3000/previous-orders
    unsubscribe: http://localhost:3000/unsubcribe?id={id}
    from: noreply@${WEBSHOP_NAME:webshop}.hu
