spring:
  mail:
    host: ${SMTP_PORT:smtp.elasticemail.com}
    port: ${SMTP_HOST:2525}
    username: ${SMTP_USERNAME:noreply@email_domain.com}
    password: ${SMTP_PASSWORD:password_placeholder}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  email:
    from: noreply@${WEBSHOP_NAME:email_domain}.hu
  payment:
    demo-mode: false
