scrape_configs:
  - job_name: 'WebShopMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]
        labels:
          application: 'Web shop engine'
    basic_auth:
      username: monitoring
      password: monitoring